menu:
  技术栈: /categories/技术/
  创业路: /categories/创业路/
  #Archives: /archives

rss: /atom.xml
description: 


social:
  #weibo: 
  #github: https://github.com/vimer
  excellent_blog: /excellent-blogs
  #facebook: 
  #twitter: 

page_comments: true
disqus_shortname: vimer

#logo: /images/logo2.jpg
background:
  cover: /images/background-cover.jpg
  #color: cover-purple
  #color: cover-slate
  color: cover-disabled
  #color: cover-origin


archive_date_format: MMM DD
fancybox: true

google_analytics: UA-70385904-1
favicon: /images/favicon.ico
